In [1]:
import numpy as np

In [23]:
mat = np.array([[5,6],
               [7,4]])
det1 = np.linalg.det(mat)
print(det1)

inv1 = np.linalg.inv(mat)
print(inv1)

t1 = np.transpose(mat)
print(t1)

print(mat*2)

adj1 = det1 * inv1
print(adj1)

rank1 = np.linalg.matrix_rank(mat)
print(rank1)

diag1 = np.diag(mat)
print(diag1)

trace1 = np.trace(mat)
print(trace1)

eigen_vector_values = np.linalg.eig(mat)
print(eigen_vector_values)

-22.000000000000004
[[-0.18181818  0.27272727]
 [ 0.31818182 -0.22727273]]
[[5 7]
 [6 4]]
[[10 12]
 [14  8]]
[[ 4. -6.]
 [-7.  5.]]
2
[5 4]
9
EigResult(eigenvalues=array([11., -2.]), eigenvectors=array([[ 0.70710678, -0.65079137],
       [ 0.70710678,  0.7592566 ]]))
