In [1]:
import numpy as np

In [15]:
A = np.array([[5,4],
              [6,2]])
B = np.array([[8,4],
              [3,2]])
add = np.add(A,B)
print(add)

sub = np.subtract(A,B)
print(sub)

mul = np.dot(A,B)
print(mul)

dev = A/B
print(dev)

[[13  8]
 [ 9  4]]
[[-3  0]
 [ 3  0]]
[[52 28]
 [54 28]]
[[0.625 1.   ]
 [2.    1.   ]]
