In [1]:
import numpy as np

In [2]:
list1 = np.array([10,20,30,40])
print(list1)

[10 20 30 40]


In [3]:
print(list1+2)
print(list1-2)
print(list1*2)
print(list1/2)

[12 22 32 42]
[ 8 18 28 38]
[20 40 60 80]
[ 5. 10. 15. 20.]


In [4]:
#aggregation function
print(np.sum(list1))

100


In [5]:
print(np.min(list1))
print(np.max(list1))
print(np.std(list1))
print(np.var(list1))

10
40
11.180339887498949
125.0


In [6]:
list2 = np.array([1,2,3,4,5,6])
print(list2[::2])

[1 3 5]


In [7]:
print(list2[[0,3,4]])

[1 4 5]


In [10]:
print(list2[list2>2])

[3 4 5 6]
