In [11]:
print("Hello world")

Hello world


In [12]:
import numpy as np 
n_array = np.array([1,2,3,4,5])
print(n_array)

[1 2 3 4 5]


In [13]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
zero = np.zeros(3)
print(zero)

[0. 0. 0.]


In [20]:
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
sp_value = np.full((2,3),7)
print(sp_value)

[[7 7 7]
 [7 7 7]]


In [31]:
ele = np.arange(1,10,2)
print(ele)

[1 3 5 7 9]


In [35]:
#eyedentity matrix
m1 = np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
