In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [3]:
a2 = np.array([
    [1,2,3],
    [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
z = np.zeros((2,2))
print(z)

[[0. 0.]
 [0. 0.]]


In [5]:
o = np.ones((2,2))
print(o)

[[1. 1.]
 [1. 1.]]


In [6]:
f = np.full((2,2),3)
print(f)

[[3 3]
 [3 3]]


In [7]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
a_data = np.arange(1,10,2)
print(a_data)

[1 3 5 7 9]


In [9]:
line_space = np.linspace(1,10,4)
print(line_space)

[ 1.  4.  7. 10.]


In [10]:
rd = np.random.rand(2,2)
print(rd)

[[0.51873891 0.75591746]
 [0.23019496 0.82157044]]


In [11]:
print(rd.shape)
print(rd.size)
print(rd.dtype)
change_datatype=rd.astype(int)
print(change_datatype)

(2, 2)
4
float64
[[0 0]
 [0 0]]


In [12]:
data = np.random.randint(1,20,10)
print(data)
print(data[::-1])

[ 7 12  3  5 15  1 16  3  4 13]
[13  4  3 16  1 15  5  3 12  7]


In [13]:
rd2 = np.random.rand(3,3)
print(rd2)

[[0.12360291 0.27024303 0.33612451]
 [0.69437698 0.15881637 0.65771199]
 [0.20034887 0.72597542 0.57762345]]


In [14]:
print(rd2[1,1])

0.15881636726230464


In [15]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
j = np.transpose(mat)
print(j)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat+2)
print(mat-2)
print(mat*2)
print(mat/2)
print(mat**2)
print(mat//2)
print(mat%2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [17]:
list2 = np.array([10,20,30,40])
print(list2)

[10 20 30 40]


In [18]:
sum1 = np.sum(list2)
print(sum1)
mean1 = np.mean(list2)
print(mean1)
max1 = np.max(list2)
print(max1)
min1 = np.min(list2)
print(min1)
std1 = np.std(list2)
print(std1)
var1 = np.var(list2)
print(var1)
median1 = np.median(list2)
print(median1)

100
25.0
40
10
11.180339887498949
125.0
25.0


In [19]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
s = np.sum(mat,axis=0)
print(s)
s = np.sum(mat,axis=1)
print(s)

[12 15 18]
[ 6 15 24]


In [20]:
mat1 = np.array([[1,2],
                [3,4]])
mat2 = np.array([[5,6],
                [7,8]])
result1 = np.dot(mat1,mat2)
print(result1)

[[19 22]
 [43 50]]


In [21]:
u = np.array([1,2,3])
v = np.array([4,5,6])
v_add = np.add(u,v)
print(v_add)
print(u*2)
dot_p = np.dot(u,v)
print(dot_p)
cross_p = np.cross(u,v)
print(cross_p)
if np.dot(u,v) == 0:
    print("Orthogonal")
else:
    print("not")

if np.all(np.cross(u,v)) == 0:
    print("Parallelism")
else:
    print("not")

[5 7 9]
[2 4 6]
32
[-3  6 -3]
not
not


In [22]:
mat1 = np.array([[1,2],
                [3,4]])

det1 = np.linalg.det(mat1)
print(det1)

-2.0000000000000004


In [23]:
inv1 = np.linalg.inv(mat1)
print(inv1)

[[-2.   1. ]
 [ 1.5 -0.5]]
