In [1]:
import numpy as np

In [2]:
list1 = np.array([10,20,30,40,50])
new_list = np.insert(list1,2,60)
print(new_list)

[10 20 60 30 40 50]


In [3]:
list_2d = np.array([[1,2],[3,4]])
newlist_2d = np.insert(list_2d,1,[5,6],axis=0)
print(newlist_2d)

[[1 2]
 [5 6]
 [3 4]]


In [4]:
x = np.append(list1,[60,70,80])
print(x)

[10 20 30 40 50 60 70 80]


In [5]:
#concatenate
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.concatenate((a,b),axis=0)
print(c)

[10 20 30 40 50 60]


In [6]:
d = np.delete(a,1)
print(d)

[10 30]
